name: iOS CI

on:
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
      - docs
      - androidApp
  workflow_dispatch: { }

concurrency:
  group: build-ios-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_ios:
    name: Build iOS app
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: iosApp/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Initialize pods
        run: ./gradlew shared:podInstall

      - name: Build with Xcode
        working-directory: ./iosApp
        run: xcodebuild -workspace iosApp.xcworkspace -scheme iosApp -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15'
